version: '3.9'

services:
  password-generator:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # Открываем стандартный ввод для взаимодействия
    tty: true        # Включаем режим псевдотерминала
